.TH "lsm_nfs_export_delete" 3 "lsm_nfs_export_delete" "October 2017" "Libstoragemgmt C API Manual" 
.SH NAME
lsm_nfs_export_delete \- Deletes the specified NFS export.
.SH SYNOPSIS
.B "int" lsm_nfs_export_delete
.BI "(lsm_connect *" conn ","
.BI "lsm_nfs_export *" e ","
.BI "lsm_flag " flags ");"
.SH ARGUMENTS
.IP "conn" 12
Valid connection.
.IP "e" 12
The pointer of lsm_nfs_export to remove.
.IP "flags" 12
Reserved for future use, must be LSM_CLIENT_FLAG_RSVD.
.SH "VERSION"
1.0
.SH "DESCRIPTION"
Deletes the specified NFS export.
.SH "CAPABILITY"
LSM_CAP_EXPORT_REMOVE
.SH "RETURN"
Error code as enumerated by 'lsm_error_number'.
    * LSM_ERR_OK
        On success.
    * LSM_ERR_NOT_FOUND_NFS_EXPORT
        When NFS export not found.
