.TH "lsm_disk_record_copy" 3 "lsm_disk_record_copy" "May 2018" "Libstoragemgmt C API Manual" 
.SH NAME
lsm_disk_record_copy \- Duplicates a lsm_disk record.
.SH SYNOPSIS
.B "lsm_disk  *" lsm_disk_record_copy
.BI "(lsm_disk *" d ");"
.SH ARGUMENTS
.IP "d" 12
Pointer of lsm_disk to duplicate.
.SH "VERSION"
1.0
.SH "DESCRIPTION"
Duplicates a lsm_disk record.
.SH "RETURN"
Pointer of lsm_disk. NULL on memory allocation failure. Should be
freed by \fBlsm_disk_record_free\fP.
