.TH "lsm_capability_get" 3 "lsm_capability_get" "May 2018" "Libstoragemgmt C API Manual" 
.SH NAME
lsm_capability_get \- Retrieves the support status of specified capability.
.SH SYNOPSIS
.B "lsm_capability_value_type" lsm_capability_get
.BI "(lsm_storage_capabilities *" cap ","
.BI "lsm_capability_type " t ");"
.SH ARGUMENTS
.IP "cap" 12
Pointer of lsm_storage_capabilities to release.
.IP "t" 12
lsm_capability_type. Capability to query. Check the document of
desired function for detail.
.SH "VERSION"
1.0
.SH "DESCRIPTION"
Retrieves the support status of specified capability.
.SH "RETURN"
lsm_capability_value_type. Possible values are:
    * LSM_CAP_SUPPORTED
        Capability is supported.
    * LSM_CAP_UNSUPPORTED
        Capability is unsupported or invalid lsm_storage_capabilities
        pointer or invalid lsm_capability_type.
