.TH "lsm_disk_vpd83_get" 3 "lsm_disk_vpd83_get" "February 2019" "Libstoragemgmt C API Manual" 
.SH NAME
lsm_disk_vpd83_get \- Retrieve the SCSI VPD 0x83 ID for the disk.
.SH SYNOPSIS
.B "const char  *" lsm_disk_vpd83_get
.BI "(lsm_disk *" d ");"
.SH ARGUMENTS
.IP "d" 12
Disk to retrieve system ID for.
.SH "VERSION"
1.3
.SH "DESCRIPTION"
Retrieve the system id for the specified disk.
Only available for direct attached storage system.
Returns the SCSI VPD83 NAA ID of disk. The VPD83 NAA ID could be used in
lsm_local_disk_vpd83_search when physical disk is exposed to OS
directly (also known as system HBA mode). Please be advised the
capability LSM_CAP_DISK_VPD83_GET only means plugin could query VPD83
for HBA mode disk, for those physical disks acting as RAID member,
plugin might return NULL as their VPD83 NAA ID.
.SH "NOTE"
Address returned is valid until lsm_disk gets freed, copy return
value if you need longer scope. Do not free returned string.
.SH "RETURN"
string. NULL if argument 'd' is NULL or not a valid lsm_disk pointer.
