.TH "lsm_volume_record_copy" 3 "lsm_volume_record_copy" "October 2017" "Libstoragemgmt C API Manual" 
.SH NAME
lsm_volume_record_copy \- Duplicates a volume record.
.SH SYNOPSIS
.B "lsm_volume  *" lsm_volume_record_copy
.BI "(lsm_volume *" vol ");"
.SH ARGUMENTS
.IP "vol" 12
Pointer of lsm_volume to duplicate.
.SH "VERSION"
1.0
.SH "DESCRIPTION"
Duplicates a lsm_volume record.
.SH "RETURN"
Pointer of lsm_volume. NULL on memory allocation failure or invalid
lsm_volume pointer. Should be freed by \fBlsm_volume_record_free\fP.
