.TH "lsm_disk_record_free" 3 "lsm_disk_record_free" "May 2018" "Libstoragemgmt C API Manual" 
.SH NAME
lsm_disk_record_free \- Free the lsm_disk memory.
.SH SYNOPSIS
.B "int" lsm_disk_record_free
.BI "(lsm_disk *" d ");"
.SH ARGUMENTS
.IP "d" 12
Record to release
.SH "VERSION"
1.0
.SH "DESCRIPTION"
Frees the memory resources for the specified lsm_disk.
.SH "RETURN"
Error code as enumerated by 'lsm_error_number':
    * LSM_ERR_OK
        On success.
    * LSM_ERR_INVALID_ARGUMENT
        When not a valid lsm_disk pointer.
