.TH "lsm_access_group_initiator_add" 3 "lsm_access_group_initiator_add" "May 2018" "Libstoragemgmt C API Manual" 
.SH NAME
lsm_access_group_initiator_add \- Adds an initiator to the access group
.SH SYNOPSIS
.B "int" lsm_access_group_initiator_add
.BI "(lsm_connect *" conn ","
.BI "lsm_access_group *" access_group ","
.BI "const char *" init_id ","
.BI "lsm_access_group_init_type " init_type ","
.BI "lsm_access_group **" updated_access_group ","
.BI "lsm_flag " flags ");"
.SH ARGUMENTS
.IP "conn" 12
Valid lsm_connect pointer.
.IP "access_group" 12
Pointer of lsm_access_group to modify.
.IP "init_id" 12
String. Initiator id to be added to group.
.IP "init_type" 12
lsm_access_group_init_type. Valid initiator types are:
* LSM_ACCESS_GROUP_INIT_TYPE_ISCSI_IQN
   iSCSI IQN.
* LSM_ACCESS_GROUP_INIT_TYPE_WWPN
   FC WWPN
.IP "updated_access_group" 12
Output pointer of the updated lsm_access_group.
Returned value must be freed with \fBlsm_access_group_record_free\fP.
.IP "flags" 12
Reserved for future use, must be LSM_CLIENT_FLAG_RSVD.
.SH "VERSION"
1.0
.SH "DESCRIPTION"
Add an initiator to the specified access group.
.SH "CAPABILITY"
LSM_CAP_ACCESS_GROUP_INITIATOR_ADD_WWPN
LSM_CAP_ACCESS_GROUP_INITIATOR_ADD_ISCSI_IQN
.SH "RETURN"
Error code as enumerated by 'lsm_error_number'.
    * LSM_ERR_OK
        On success.
    * LSM_ERR_INVALID_ARGUMENT
        When any argument is NULL or not a valid lsm_connect pointer
        or invalid flags or invalid lsm_access_group pointer or
        illegal initiator or invalid init_type.
    * LSM_ERR_NOT_FOUND_ACCESS_GROUP
        When access group not found.
    * LSM_ERR_EXISTS_INITIATOR
        When specified initiator is in other access group.
    * LSM_ERR_NO_STATE_CHANGE
        When specified initiator is already in specified access group.
    * LSM_ERR_NO_SUPPORT
        Not supported.
