.TH "lsm_access_group_name_get" 3 "lsm_access_group_name_get" "May 2018" "Libstoragemgmt C API Manual" 
.SH NAME
lsm_access_group_name_get \- Retrieves the name for the access group.
.SH SYNOPSIS
.B "const char  *" lsm_access_group_name_get
.BI "(lsm_access_group *" group ");"
.SH ARGUMENTS
.IP "group" 12
Access group to retrieve name for.
.SH "VERSION"
1.0
.SH "DESCRIPTION"
Retrieves the name for the access group.
.SH "NOTE"
Address returned is valid until lsm_access_group gets freed, copy
return value if you need longer scope. Do not free returned string.
.SH "RETURN"
string. NULL if argument 'group' is NULL or not a valid lsm_access_group
pointer.
