.TH "lsm_nfs_export_record_array_free" 3 "lsm_nfs_export_record_array_free" "October 2017" "Libstoragemgmt C API Manual" 
.SH NAME
lsm_nfs_export_record_array_free \- Free the memory of lsm_nfs_export array.
.SH SYNOPSIS
.B "int" lsm_nfs_export_record_array_free
.BI "(lsm_nfs_export *" exps[] ","
.BI "uint32_t " size ");"
.SH ARGUMENTS
.IP "exps[]" 12
Array to release memory for.
.IP "size" 12
Number of elements.
.SH "VERSION"
1.0
.SH "DESCRIPTION"
Frees the memory resources for an array of lsm_nfs_export.
.SH "RETURN"
Error code as enumerated by 'lsm_error_number':
    * LSM_ERR_OK
        On success.
    * LSM_ERR_INVALID_ARGUMENT
        When not a valid lsm_nfs_export pointer.
