.TH "lsm_disk_id_get" 3 "lsm_disk_id_get" "May 2018" "Libstoragemgmt C API Manual" 
.SH NAME
lsm_disk_id_get \- Retrieves the ID of the disk.
.SH SYNOPSIS
.B "const char  *" lsm_disk_id_get
.BI "(lsm_disk *" d ");"
.SH ARGUMENTS
.IP "d" 12
Disk to retrieve id for.
.SH "VERSION"
1.0
.SH "DESCRIPTION"
Retrieves the ID for the disk.
.SH "NOTE"
Address returned is valid until lsm_disk gets freed, copy return
value if you need longer scope. Do not free returned string.
.SH "RETURN"
string. NULL if argument 'd' is NULL or not a valid lsm_disk pointer.
