.TH "lsm_fs_child_dependency" 3 "lsm_fs_child_dependency" "February 2019" "Libstoragemgmt C API Manual" 
.SH NAME
lsm_fs_child_dependency \- Checks whether file system has a child dependency.
.SH SYNOPSIS
.B "int" lsm_fs_child_dependency
.BI "(lsm_connect *" conn ","
.BI "lsm_fs *" fs ","
.BI "lsm_string_list *" files ","
.BI "uint8_t *" yes ","
.BI "lsm_flag " flags ");"
.SH ARGUMENTS
.IP "conn" 12
Valid connection.
.IP "fs" 12
Point of lsm_fs.
.IP "files" 12
Pointer of lsm_string_list. Only check on specific files if defined.
If NULL, just check the file system.
.IP "yes" 12
uint8_t. 1 == Yes, 0 == No
.IP "flags" 12
Reserved for future use, must be LSM_CLIENT_FLAG_RSVD.
.SH "VERSION"
1.0
.SH "DESCRIPTION"
Returns 1 if the specified file system has child dependencies, else
returns 0.
.SH "CAPABILITY"
LSM_CAP_FS_CHILD_DEPENDENCY
.SH "RETURN"
Error code as enumerated by 'lsm_error_number'.
    * LSM_ERR_OK
        On success.
    * LSM_ERR_INVALID_ARGUMENT
        When any argument is NULL or not a valid lsm_connect pointer
        or invalid flags or invalid file system.
    * LSM_ERR_NOT_FOUND_FS
        When file system not found.
    * LSM_ERR_NO_SUPPORT
        Not supported.
