.TH "lsm_iscsi_chap_auth" 3 "lsm_iscsi_chap_auth" "February 2019" "Libstoragemgmt C API Manual" 
.SH NAME
lsm_iscsi_chap_auth \- Set iSCSI CHAP authentication.
.SH SYNOPSIS
.B "int" lsm_iscsi_chap_auth
.BI "(lsm_connect *" conn ","
.BI "const char *" init_id ","
.BI "const char *" in_user ","
.BI "const char *" in_password ","
.BI "const char *" out_user ","
.BI "const char *" out_password ","
.BI "lsm_flag " flags ");"
.SH ARGUMENTS
.IP "conn" 12
Valid connection pointer
.IP "init_id" 12
String. The iSCSI Initiator IQN.
.IP "in_user" 12
String. The inbound user name
.IP "in_password" 12
String. The inbound password
.IP "out_user" 12
String. The outbound user name
.IP "out_password" 12
String. The outbound password
.IP "flags" 12
Reserved for future use, must be LSM_CLIENT_FLAG_RSVD.
.SH "VERSION"
1.0
.SH "DESCRIPTION"
Set the username password for iSCSI CHAP authentication, inbound and
outbound.
.SH "RETURN"
Error code as enumerated by 'lsm_error_number'.
    * LSM_ERR_OK
        On success.
    * LSM_ERR_INVALID_ARGUMENT
        When not a valid lsm_connect pointer or invalid flags.
    * LSM_ERR_NO_SUPPORT
        Not supported.
