.TH "lsm_fs_record_copy" 3 "lsm_fs_record_copy" "February 2019" "Libstoragemgmt C API Manual" 
.SH NAME
lsm_fs_record_copy \- Duplicates a lsm_fs record.
.SH SYNOPSIS
.B "lsm_fs  *" lsm_fs_record_copy
.BI "(lsm_fs *" source ");"
.SH ARGUMENTS
.IP "source" 12
Pointer of lsm_fs to duplicate.
.SH "VERSION"
1.0
.SH "DESCRIPTION"
Duplicates a lsm_fs record.
.SH "RETURN"
Pointer of lsm_fs. NULL on memory allocation failure or argument
\fIsource\fP is NULL. Should be freed by \fBlsm_fs_record_free\fP.
