.TH "lsm_string_list_elem_get" 3 "lsm_string_list_elem_get" "February 2019" "Libstoragemgmt C API Manual" 
.SH NAME
lsm_string_list_elem_get \- Retrieve specified index of string from lsm_string_list.
.SH SYNOPSIS
.B "const char  *" lsm_string_list_elem_get
.BI "(lsm_string_list *" sl ","
.BI "uint32_t " index ");"
.SH ARGUMENTS
.IP "sl" 12
lsm_string_list. The string list to retrieve from.
.IP "index" 12
uint32_t. The index of element string to retrieve. Starting from 0.
.SH "VERSION"
1.0
.SH "DESCRIPTION"
Retrieves specified index of string from lsm_string_list.
.SH "NOTE"
Address returned is valid until lsm_string_list gets freed, copy
return value if you need longer scope. Do not free returned string.
.SH "RETURN"
string. NULL if argument 'sl' is NULL or not a valid
lsm_string_list pointer or out of index.
