.TH "lsm_block_range_dest_start_get" 3 "lsm_block_range_dest_start_get" "May 2018" "Libstoragemgmt C API Manual" 
.SH NAME
lsm_block_range_dest_start_get \- Retrieves start block of the destination.
.SH SYNOPSIS
.B "uint64_t" lsm_block_range_dest_start_get
.BI "(lsm_block_range *" br ");"
.SH ARGUMENTS
.IP "br" 12
Block range to retrieve destination start block number.
.SH "VERSION"
1.0
.SH "DESCRIPTION"
Retrieves the destination start block number of the replication
destination.
.SH "RETURN"
uint64_t. 0 if invalid lsm_block_range pointer.
