.TH "lsm_access_group_init_type_get" 3 "lsm_access_group_init_type_get" "February 2019" "Libstoragemgmt C API Manual" 
.SH NAME
lsm_access_group_init_type_get \- Retrieves the initiator type for specified access group.
.SH SYNOPSIS
.B "lsm_access_group_init_type" lsm_access_group_init_type_get
.BI "(lsm_access_group *" group ");"
.SH ARGUMENTS
.IP "group" 12
Access group to retrieve type of initiators present.
.SH "VERSION"
1.7
.SH "DESCRIPTION"
Retrieves the initiator type for the specified access group.
.SH "RETURN"
lsm_access_group_init_type
