.TH "lsm_pool_status_info_get" 3 "lsm_pool_status_info_get" "February 2019" "Libstoragemgmt C API Manual" 
.SH NAME
lsm_pool_status_info_get \- Retrieve the status information for pool.
.SH SYNOPSIS
.B "const char  *" lsm_pool_status_info_get
.BI "(lsm_pool *" s ");"
.SH ARGUMENTS
.IP "s" 12
Pool to retrieve status information for.
.SH "VERSION"
1.0
.SH "DESCRIPTION"
Retrieves the status information of specified pool.
Normally it explains the status value.
.SH "NOTE"
Address returned is valid until lsm_pool gets freed, copy return
value if you need longer scope. Do not free returned string.
.SH "RETURN"
string. NULL if argument 's' is NULL or not a valid lsm_pool pointer.
