.TH "lsm_connect_password" 3 "lsm_connect_password" "February 2019" "Libstoragemgmt C API Manual" 
.SH NAME
lsm_connect_password \- Get a connection to a storage provider.
.SH SYNOPSIS
.B "int" lsm_connect_password
.BI "(const char *" uri ","
.BI "const char *" password ","
.BI "lsm_connect **" conn ","
.BI "uint32_t " timeout ","
.BI "lsm_error_ptr *" e ","
.BI "lsm_flag " flags ");"
.SH ARGUMENTS
.IP "uri" 12
Uniform Resource Identifier (see URI documentation)
.IP "password" 12
Password for the storage array (optional, can be NULL)
.IP "conn" 12
The connection to use for all the other library calls.
When done using the connection it must be freed with a call to
\fBlsm_connect_close\fP.
.IP "timeout" 12
Time-out in milliseconds, (initial value).
.IP "e" 12
Error data if connection failed.
.IP "flags" 12
Reserved for future use, must be LSM_CLIENT_FLAG_RSVD.
.SH "VERSION"
1.0
.SH "DESCRIPTION"
Get a connection to a storage provider.
.SH "RETURN"
Error code as enumerated by 'lsm_error_number'.
    * LSM_ERR_OK
        On success.
    * LSM_ERR_INVALID_ARGUMENT
        When any argument is NULL or invalid flags.
