.TH "lsm_error_exception_get" 3 "lsm_error_exception_get" "October 2017" "Libstoragemgmt C API Manual" 
.SH NAME
lsm_error_exception_get \- Retrieves the exception message from the error.
.SH SYNOPSIS
.B "char  *" lsm_error_exception_get
.BI "(lsm_error_ptr " e ");"
.SH ARGUMENTS
.IP "e" 12
The lsm_error to retrieves exception message from.
.SH "VERSION"
1.0
.SH "DESCRIPTION"
Retrieves the exception message for the specified lsm_error.
.SH "NOTE"
Address returned is valid until lsm_error gets freed, copy return
value if you need longer scope. Do not free returned string.
.SH "RETURN"
string. NULL if argument 'e' is NULL or not a valid lsm_error_ptr.
