.TH "lsm_volume_number_of_blocks_get" 3 "lsm_volume_number_of_blocks_get" "October 2017" "Libstoragemgmt C API Manual" 
.SH NAME
lsm_volume_number_of_blocks_get \- Retrieves the block count for the volume.
.SH SYNOPSIS
.B "uint64_t" lsm_volume_number_of_blocks_get
.BI "(lsm_volume *" v ");"
.SH ARGUMENTS
.IP "v" 12
Volume to retrieve block count for.
.SH "VERSION"
1.0
.SH "DESCRIPTION"
Retrieves the block count for the volume.
.SH "RETURN"
uint64_t. 0 if argument 'v' is NULL or not a valid lsm_volume pointer.
