.TH "lsm_target_port_copy" 3 "lsm_target_port_copy" "February 2019" "Libstoragemgmt C API Manual" 
.SH NAME
lsm_target_port_copy \- Duplicates a lsm_target_port record.
.SH SYNOPSIS
.B "lsm_target_port  *" lsm_target_port_copy
.BI "(lsm_target_port *" tp ");"
.SH ARGUMENTS
.IP "tp" 12
Pointer of lsm_target_port to duplicate.
.SH "VERSION"
1.0
.SH "DESCRIPTION"
Duplicates a lsm_target_port record.
.SH "RETURN"
Pointer of lsm_target_port. NULL on memory allocation failure or invalid
lsm_target_port pointer. Should be freed by
\fBlsm_target_port_record_free\fP.
