.TH "lsm_access_group_record_free" 3 "lsm_access_group_record_free" "February 2019" "Libstoragemgmt C API Manual" 
.SH NAME
lsm_access_group_record_free \- Frees the memory for access group.
.SH SYNOPSIS
.B "int" lsm_access_group_record_free
.BI "(lsm_access_group *" group ");"
.SH ARGUMENTS
.IP "group" 12
lsm_access_group to release memory for.
.SH "VERSION"
1.0
.SH "DESCRIPTION"
Frees the memory for an individual lsm_access_group.
.SH "RETURN"
Error code as enumerated by 'lsm_error_number':
    * LSM_ERR_OK
        On success or not found.
    * LSM_ERR_INVALID_ARGUMENT
        When any argument is NULL or not a valid lsm_access_group
        pointer.
